baseURL: 'https://radkomih.github.io/blog/'
languageCode: en-us
title: Random Thoughts
theme: PaperMod
params:
  homeInfoParams:
    Title: Hi there 👋
    Content: Welcome to my blog!

  socialIcons:
      - name: "Github"
        url: "https://github.com/radkomih"
      - name: "Twitter"
        url: "https://twitter.com/radkomih"
      - name: "Resume"
        url: "https://radkomih.github.io/page/"

  defaultTheme: auto
  hideSummary: true
  ShowReadingTime: true